const quotesArcanumDivinaeSapientiae = [
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.family.foundation_of_society"],
    author: "Pope_Leo_XIII",
    author_type: "Pope",
    doctype: "encyclical",
    indocreference: "4",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblycondemned: "no",
    quote:
      "Wondrous, indeed, was the extent of dignity, steadfastness, and goodness which thus accrued to the State as well as to the family. The authority of rulers became more just and revered; the obedience of the people more ready and unforced; the union of citizens closer; the rights of dominion more secure. In very truth, the Christian religion thought of and provided for all things which are held to be advantageous in a State; so much so, indeed, that, according to St. Augustine, one cannot see how it could have offered greater help in the matter of living well and happily, had it been instituted for the single object of procuring or increasing those things which contributed to the conveniences or advantages of this mortal life.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.family.foundation_of_society.foundation_of_family"],
    author: "Pope_Leo_XIII",
    author_type: "Pope",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblycondemned: "no",
    quote:
      "Our wish is rather to speak about that family union of which marriage is the beginning and the foundation.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.origin"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "5",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "The true origin of marriage, venerable brothers, is well known to all. Though revilers of the Christian faith refuse to acknowledge the never-interrupted doctrine of the Church on this subject, and have long striven to destroy the testimony of all nations and of all times, they have nevertheless failed not only to quench the powerful light of truth, but even to lessen it. We record what is to all known, and cannot be doubted by any, that God, on the sixth day of creation, having made man from the slime of the earth, and having breathed into his face the breath of life, gave him a companion, whom He miraculously took from the side of Adam when he was locked in sleep. God thus, in His most far-reaching foresight, decreed that this husband and wife should be the natural beginning of the human race, from whom it might be propagated and preserved by an unfailing fruitfulness throughout all futurity of time.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.indissolubility"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "5",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "And this union of man and woman, that it might answer more fittingly to the infinite wise counsels of God, even from the beginning manifested chiefly two most excellent properties — deeply sealed, as it were, and signed upon it — namely, unity and perpetuity. From the Gospel we see clearly that this doctrine was declared and openly confirmed by the divine authority of Jesus Christ. He bore witness to the Jews and to His Apostles that marriage, from its institution, should exist between two only, that is, between one man and one woman; that of two they are made, so to say, one flesh; and that the marriage bond is by the will of God so closely and strongly made fast that no man may dissolve it or render it asunder.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.indissolubility"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "8",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "Hence, having set aside the difficulties which were adduced from the law of Moses, He, in character of supreme Lawgiver, decreed as follows concerning husbands and wives, “I say to you, that whosoever shall put away his wife, except it be for fornication, and shall marry another, committeth adultery; and he that shall marry her that is put away committeth adultery.”",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.sacrament"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "9",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "To the Apostles, indeed, as our masters, are to be referred the doctrines which “our holy Fathers, the Councils, and the Tradition of the Universal Church have always taught,”[9] namely, that Christ our Lord raised marriage to the dignity of a sacrament; that to husband and wife, guarded and strengthened by the heavenly grace which His merits Rained for them, He gave power to attain holiness in the married state",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.like_mystical_union", "marriage.indissolubility"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "9",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "in a wondrous way, making marriage an example of the mystical union between Himself and His Church, He not only perfected that love which is according to nature,[10] but also made the naturally indivisible union of one man with one woman far more perfect through the bond of heavenly love.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.indissolubility"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "9",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "In like manner from the teaching of the Apostles we learn that the unity of marriage and its perpetual indissolubility, the indispensable conditions of its very origin, must, according to the command of Christ, be holy and inviolable without exception.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.procreation_purpose"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "10",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "By the command of Christ, it not only looks to the propagation of the human race, but to the bringing forth of children for the Church",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["marriage.wives_obey_husbands"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "11",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "The husband is the chief of the family and the head of the wife. The woman, because she is flesh of his flesh, and bone of his bone, must be subject to her husband and obey him; not, indeed, as a servant, but as a companion, so that her obedience shall be wanting in neither honor nor dignity.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: [
      "marriage.helpmate_purpose",
      "marriage.husbands_love_wives",
      "marriage.husband_role",
      "marriage.wife_role",
    ],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "11",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "the mutual duties of husband and wife have been defined, and their several rights accurately established. They are bound, namely, to have such feelings for one another as to cherish always very great mutual love, to be ever faithful to their marriage vow, and to give one another an unfailing and unselfish help.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: [
      "marriage.like_mystical_union",
      "marriage.husband_role",
      "marriage.wife_role",
      "marriage.wives_obey_husbands",
      "marriage.husbands_love_wives",
    ],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "11",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "Since the husband represents Christ, and since the wife represents the Church, let there always be, both in him who commands and in her who obeys, a heaven-born love guiding both in their respective duties.",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["parenting.children_obey_parents"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "12",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "As regards children, they ought to submit to the parents and obey them, and give them honor for conscience’ sake",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: ["parenting.parent_duties"],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "12",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "parents are bound to give all care and watchful thought to the education of their offspring and their virtuous bringing up",
  },
  {
    publication: "Arcanum Divinae Sapientiae",
    topictree: [
      "marriage.sacrament",
      "marriage.husband_role",
      "marriage.wife_role",
    ],
    author: "Pope_Leo_XIII",
    authortype: "Pope",
    doctype: "enyclical",
    indocreference: "12",
    date: "1880_Feb_10",
    infalliblytrue: "no",
    infalliblyfalse: "no",
    quote:
      "the duties of husbands and wives are neither few nor light; although to married people who are good these burdens become not only bearable but agreeable, owing to the strength which they gain through the sacrament.",
  },
];

const quotesCorinthians1 = [
  {
    publication: "1 Corinthians",
    topictree: ["marriage.death_ends_marriage", "marriage.indissolubility"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["7", "39"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[39] A woman is bound by the law as long as her husband liveth; but if her husband die, she is at liberty: let her marry to whom she will; only in the Lord.",
  },
  {
    publication: "1 Corinthians",
    topictree: ["marriage.lower_than_celibacy"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["7", "40"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "But more blessed shall she be, if she so remain, according to my counsel; and I think that I also have the spirit of God",
  },
];

const quotesEphesians = [
  {
    publication: "Ephesians",
    topictree: ["marriage.sacrament"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "32"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[32] This is a great sacrament; but I speak in Christ and in the church.",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.one_flesh"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "31"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[31] For this cause shall a man leave his father and mother, and shall cleave to his wife, and they shall be two in one flesh.",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.wives_obey_husbands"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: "5,33",
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[33] Nevertheless let every one of you in particular love his wife as himself: and let the wife fear her husband.",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.wives_obey_husbands"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: "5,22",
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote: "[22] Let women be subject to their husbands, as to the Lord",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.wives_obey_husbands"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "23"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[23] Because the husband is the head of the wife, as Christ is the head of the church.",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.wives_obey_husbands"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "24"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[24] Therefore as the church is subject to Christ, so also let the wives be to their husbands in all things.",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.husbands_love_wives"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "25"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[25] Husbands, love your wives, as Christ also loved the church, and delivered himself up for it:",
  },
  {
    publication: "Ephesians",
    topictree: ["marriage.husbands_love_wives"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["5", "28"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[28] So also ought men to love their wives as their own bodies. He that loveth his wife, loveth himself.",
  },
  {
    publication: "Ephesians",
    topictree: ["parenting.children_obey_parents"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["6", "1"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote: "[1] Children, obey your parents in the Lord, for this is just.",
  },
  {
    publication: "Ephesians",
    topictree: ["parenting.honor_thy_father_and_mother"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["6", "2"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[2] Honour thy father and thy mother, which is the first commandment with a promise",
  },
  {
    publication: "Ephesians",
    topictree: ["parenting.father_role"],
    author: "Paul",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Epistle",
    indocreference: ["6", "4"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[4] And you, fathers, provoke not your children to anger; but bring them up in the discipline and correction of the Lord.",
  },
];

const quotesGenesis = [
  {
    publication: "Genesis",
    topictree: ["marriage.origin"],
    author: undefined,
    authortype: undefined,
    doctype: "sacred_scripture",
    indocreference: ["1", "21-24"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblyfalse: undefined,
    quote:
      "[21] Then the Lord God cast a deep sleep upon Adam: and when he was fast asleep, he took one of his ribs, and filled up flesh for it. [22] And the Lord God built the rib which he took from Adam into a woman: and brought her to Adam. [23] And Adam said: This now is bone of my bones, and flesh of my flesh; she shall be called woman, because she was taken out of man. [24] Wherefore a man shall leave father and mother, and shall cleave to his wife: and they shall be two in one flesh.",
  },
];

const quotesMatthew = [
  {
    publication: "Matthew",
    topictree: ["marriage.indissolubility"],
    author: "Matthew",
    author_type: "Apostle",
    doctype: "Sacred_Scripture.Gospel",
    indocreference: ["19", "9"],
    date: undefined,
    infalliblytrue: undefined,
    infalliblycondemned: undefined,
    quote:
      "[9] And I say to you, that whosoever shall put away his wife, except it be for fornication, and shall marry another, committeth adultery: and he that shall marry her that is put away, committeth adultery.",
  },
];

const quotes = [
  ...quotesArcanumDivinaeSapientiae,
  ...quotesCorinthians1,
  ...quotesEphesians,
  ...quotesGenesis,
  ...quotesMatthew,
];

module.exports = { quotes };
